services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--mysqlx=0"]
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_HOST:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - dealflow

  n8n:
    build:
      context: .
      dockerfile: docker/n8n.Dockerfile
      args:
        APP_SOURCE_STRATEGY: local
        APP_GIT_REPO: ""
        APP_GIT_REF: main
    restart: unless-stopped
    user: root
    env_file:
      - .env.docker
    environment:
      DB_TYPE: mysqldb
      DB_MYSQLDB_HOST: db
      DB_MYSQLDB_PORT: 3306
      DB_MYSQLDB_DATABASE: ${DB_NAME}
      DB_MYSQLDB_USER: ${DB_USER}
      DB_MYSQLDB_PASSWORD: ${DB_PASSWORD}
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      GENERIC_TIMEZONE: ${TZ}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_DIAGNOSTICS_ENABLED: 'false'
      NODE_FUNCTION_ALLOW_EXTERNAL: jsonwebtoken,mysql2
      NODE_FUNCTION_ALLOW_BUILTIN: '*'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - type: volume
        source: n8n_workflows
        target: /data/workflows
      - type: volume
        source: n8n_extensions
        target: /home/node/.n8n/custom
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "mkdir -p /data/workflows /home/node/.n8n/custom &&
       cp -R /workspace/n8n/workflows/* /data/workflows/ 2>/dev/null || true &&
       cp -R /workspace/n8n/functions/* /home/node/.n8n/custom/ 2>/dev/null || true &&
       npm install --prefix /home/node/.n8n jsonwebtoken mysql2 &&
       echo 'Starting n8n...' &&
       n8n start"
    networks:
      - dealflow

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        APP_SOURCE_STRATEGY: local
        APP_GIT_REPO: ""
        APP_GIT_REF: main
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_APP_ENV: ${VITE_APP_ENV}
      CHOKIDAR_USEPOLLING: 'true'
    depends_on:
      - n8n
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    networks:
      - dealflow

volumes:
  mysql_data:
  n8n_data:
  n8n_workflows:
  n8n_extensions:

networks:
  dealflow:
    driver: bridge
